project:
  type: book
  output-dir: docs

toc: true
number-sections: true
toc-depth: 2
number-depth: 4
bibliography: book.bib
csl: ims.csl

execute:
  freeze: auto


jupyter: ds24

knitr:
  opts_chunk:
    comment: "#>"
    collapse: true



format:
  html:
    theme: united 
    # page-layout: article
    # include-before-body: 
    # - file: contents/math.qmd
crossref:
  appendix-title: "Appendix "
  appendix-delim: ":"
book:
  title: "Stats"
  subtitle: "Notes"
  description: "Homepage Spring 2024."
  author: "Xinli Xiao"
  date: last-modified
  chapters: 
    - index.qmd
    - part: contents/0/rv.qmd
      chapters:
          - contents/0/prob.qmd 
          - contents/0/basics.qmd
          - contents/0/inferences.qmd
          - contents/0/statsmodels.qmd
    - part: contents/1/notations.qmd
      chapters: 
        - contents/1/dist/binom.qmd
        - contents/1/dist/beta.qmd
        - contents/1/dist/chisquare.qmd
        - contents/1/dist/poisson.qmd
        - contents/1/dist/gamma.qmd
    #     - contents/1/dist/exp.qmd
        - contents/1/dist/normal.qmd
    - part: "SLR"
      chapters:
        - contents/2/slr.qmd
  appendices:
    - contents/app/specialfunctions.qmd
  sidebar:
    # background: "#D9E3E4"
    border: true
    search: true
    collapse-level: 1
    pinned: true
    # style: docked
    align: center
    # tools:
    #   - icon: github
    #     text: Source Code
    #     href: https://github.com/xiaoxl/stats
  # navbar:
  #   subtitle: "2023 Fall"
  #   pinned: false
  page-navigation: true







